### ISSUE TITLE
Add gosimple?

### ISSUE THREAD

**Issue by dominikh** [alecthomas/gometalinter#109]
Would [gosimple](https://github.com/dominikh/go-simple) be a candidate for inclusion in gometalinter? It's a golint derivative that focuses on code simplifications instead of a style guide. The README contains an exhaustive list of checks it performs.

**Comment by GarethLewin** [comment]
@dominikh I already tried it last night and it found a couple of issues in my code already so Thanks!

I was going to try to work on a PR for gometalinter with it, I suspect that would be the fastest way for it to get integrated?

If you would do it that would be great (since it's your tool), but if you don't have the time I'll give it a try.

**Comment by dominikh** [comment]
I can absolutely write the PR, but I wanted to get approval before sending a PR, so it wouldn't look too pushy.

**Comment by dominikh** [comment]
Oops: 91a0b0721f2fb518b84b02b0958d5a2044c2dbc9 – I guess my tool already made the rounds :)

**Comment by alecthomas** [comment]
👍
