### ISSUE TITLE
gometalinter should not exit with 1 if there are only warnings

### ISSUE THREAD

**Issue by tbroyer** [alecthomas/gometalinter#133]
When running gometalinter in a CI build, I'd like it to fail the build only when there are errors; but I want warnings displayed on the console so I can't just use `--errors`.

`gometalinter` should only exit with a status of `1` if there are errors, otherwise the distinction between warnings and errors is almost useless in the configuration.  
Either that, or it should be made an option; maybe something like similar to GCC's and JavaC's `-Werror` (which means that the default still is to return a `0` status when there are no errors)

**Comment by alecthomas** [comment]
Well, the problem is that unless the underlying linter explicitly supports warnings and errors, the only differentiation is what I've made manually in gometalinter. To summarise, warnings may be errors and errors may be warnings. It's best effort basically.

gometalinter isn't smart enough to make a determination whether an issue is really a warning or an error. For that reason, I don't think it's possible to achieve what you want.

**Comment by tbroyer** [comment]
Correct me if I'm wrong but AFAICT, the severity level is set once per linter, independently of the linter's message, so it's not about "being smart", but only about configuration.

BTW, when running with `--errors`, the `linterSeverityFlag` should probably be consulted (given that the default is `warning`) to only run the linters that **will** produce errors.
