### ISSUE TITLE
Vendor directory not ignored by --vendor flag.

### ISSUE THREAD

**Issue by EcofitBrendan** [alecthomas/gometalinter#143]
Our build server started encountering errors this morning due to vendored code being run through gometalinter in spite of the --vendor flag being set.

I dug back and found that the behaviour is present from [this commit ](https://github.com/alecthomas/gometalinter/commit/53ad2aad8be0ff0a12d4e304f099701905130ba2) onwards.

In our case, we are running: gometalinter    --vendor    --tests    --exclude=mock    --disable-all    --enable=vet    --enable=vetshadow    --enable=golint    --enable=ineffassign    --enable=goconst    --enable=goimports    ./...

**Comment by EcofitBrendan** [comment]
Note, this can be resolved as of now by setting --exclude=vendor, though this seems confusing given the presence of a specific vendoring flag.

**Comment by alecthomas** [comment]
Are you sure it wasn't ea0aeb74f1183206c3d6db09adbb83636045405b that introduced the issue?

**Comment by EcofitBrendan** [comment]
Surprisingly, no, though it could be a change from that commit interacting with another change further on.  If I check that commit out and `go install` it, the issue is not present.

**Comment by GarethLewin** [comment]
The problem is that `vendor` is not a directory that follows the special rules of go folders (it neither starts with an underscore, is a symlink or is a the word `internal`). Our solution is to create a differently named folder (`_vendor` for example) and symlink it to `vendor`, that creates an environment that all the different tools work correctly in.

It's nice that gometalinter tries to assist with the `--vendor` folder, but it's really plugging a problem that will occur in all your tools, for example `go test ./...` or `go generate ./...`

**Comment by EcofitBrendan** [comment]
This patch has resolved the issue.
