### ISSUE TITLE
goconst only accepts one directory at a time

### ISSUE THREAD

**Issue by alecthomas** [alecthomas/gometalinter#313]
```
  goconst ARGS <directory>
```

cc @dnephin

**Comment by alecthomas** [comment]
@dnephin I've rolled back your PR until this, #312, and #307 can be fixed.

**Comment by dnephin** [comment]
Ok, thanks. #312 should be easy, this one and 307 need more investigation.

**Comment by dnephin** [comment]
I think I'll start by making the regression test suite multi-directory. I hope that will expose these bugs in the test suite and make it easier to fix.

**Comment by alecthomas** [comment]
I think each linter needs something like a `PartitioningMode` enum, with `PartitionByArgLength` and `PartitionByDirectory`.  That would cover both cases AFAICT.

**Comment by alecthomas** [comment]
Also #306 needs to be reimplemented.

**Comment by dnephin** [comment]
I think there are more than 2 cases. I'm seeing these 4:
1. all packages (the default in #289, partition on max arg bytes)
2. all files (the `linterTakesFiles` option in #289, partition on max arg bytes)
3. individual packages (for goconst only, partition as separate packages)
4. file globs separated by packages (for `go vet` #307)

The old behaviour (before #289) was to only have 3 and 4.

I don't see any reason that `goconst` couldn't handle multiple paths. Instead of implementing 3 I'm going to patch `gocosnt`.

**Comment by dnephin** [comment]
My patch was accepted in goconst, so we're down to 3 cases
