### ISSUE TITLE
vet linter fails when run against a directory with multiple packages

### ISSUE THREAD

**Issue by dnephin** [alecthomas/gometalinter#351]
Two packages per directory is a common way of providing `example_test.go` for godoc examples, so that the examples can import the package as a user would:
 * https://github.com/gotestyourself/gotestyourself/tree/master/fs has both `fs` and `fs_test` package
 * https://github.com/decred/dcrutil/tree/master/bloom has both `bloom` and `bloom_test` packages

`go vet` fails on these directories because it is called with `*.go` and from the vet docs:

> vets the files named, all of which must be in the same package.

Unfortunately the other argument options (directory, and package path) are not acceptable because they are recursive or don't support shadow (respectively).

The current workaround is to [exclude `example_test.go` ](https://github.com/gotestyourself/gotestyourself/blob/master/gometalinter.json#L5) however that means that the examples will not be linted at all.

The only solution I see to this problem is to fork `go vet`, add a `--no-recursive` flag, and use that fork as the vendoered linter for `vet` and `vetshadow`.

**Comment by dnephin** [comment]
This may also be an issue with `gotype` once #348 is fixed, since it will be using the same partition strategy as `vet`.

**Comment by dnephin** [comment]
Another workaround would be to change the partition strategy for `vet` to be `single-directory` using https://github.com/alecthomas/gometalinter/pull/352/commits/5d25f28f7104d71f71d91d3e8ba2f4b0da84bb29 (not yet merged).

This would only be appropriate on small projects where there are no nested package.

**Comment by teknico** [comment]
This seems to be the same problem as #218, the [gist](https://gist.github.com/itsjamie/53d2f49643e722882845c4f50835e4fd) in the fourth comment exemplifies it.

**Comment by GoLangsam** [comment]
[Go Report Card](http://goreportcard.com/) is not only a fine and increasingly popular service, but also a proud user of Your versatile and powerful `metalinter`.

Suffering similar annoyances, [here](https://github.com/gojp/goreportcard/issues/113#issuecomment-332070468) is what I found about underlying reasons.

@dnephin IMHO I think Your view on the issue seems to differ: You worry about partitioning.
I worried (mainly) about having or not having a workspace (`$GOROOT` set or not properly set) when tooling `*.go` files .

I'd be surprised to see `go tools` not being aware enough to handle a related `*_test` package in same package-dir properly. But I'd be happy to see You filing an issue.

Anyway. As I've said [there]: I'd humbly like to recommend:
- Stay far away from non-standard use of package pointers when using `go tool`s!
Mind You: packages (not files) are the important atomic things in `go` which result in artifacts / object code.

**Comment by alecthomas** [comment]
Can anyone verify if this is fixed?

**Comment by dnephin** [comment]
@alecthomas it is not fixed, I just tried with my gotestyourself project. There are workarounds for some projects. 

You can use `PartitionStrategy: "single-directory"` **if** there are no go files in the root of the project. `vet` does recursive for directories paths so it will include `vendor/` and other ignored paths if there are go files in the root.

The default of `PartitionStrategy: "files-by-package"` works for most cases, but fails with this multi-package-in-single-dir case.

Using this config (command `go vet` instead of `go tool vet`):

```json
Linters: {
      "vet": {
          "Command": "go vet",
          "PartitionStrategy": "packages"
      }
  },
```

seems to work for those two cases, but doesn't support `-shadow`.

So there is no argument that `vet` accepts which has the correct behaviour necessary for `gometalinter` and works in all cases.

I'm going to see about a fork of `go vet` that adds a `-no-recurse` flag

**Comment by dnephin** [comment]
Opened #375 with a possible fix
