### ISSUE TITLE
Add CI section to config file format?

### ISSUE THREAD

**Issue by hasufell** [alecthomas/gometalinter#415]
Idea:

Optionally allow to have _sections_ in the config file, instead of multiple files, possibly overwriting a default setting.

Use case:

* use gometalinter for Jenkins with only errors enabled
* use _almost_ the same configuration for e.g. `make test` or the developers local editor

Theoretically one could use two files, but I feel this may more quickly introduce inconsistency. Having the config in one place for both things will probably less likely introduce divergence.

**Comment by dnephin** [comment]
I don't think I understand the use cases for different configs. Could you elaborate on why it's necessary (or even desirable) to run different linting in CI vs locally?

FYI you can use command line flags (ex: `--config config.json --disable x ...`) to further customize the config.

**Comment by hasufell** [comment]
> to run different linting in CI vs locally

Some linting is just disruptive locally (people use gometalinter within vim/emacs) and not desired by developers, while for CI we always want the full backlog of linting warnings/errors.

> FYI you can use command line flags

Yeah, as I said in the issue post: that might more quickly lead to divergence. The idea is to derive a config from another and only overwrite/change specific fields, without having to maintain them both separately.

**Comment by alecthomas** [comment]
I have to admit I would it useful if I could have separate sections for live linting within my editor, and CI linting. That said, people already have quite a few issues with `--enable`, `--disable`, `--linter`, etc. and how they interact. I suspect that adding sections to the config would only increase this confusion.

**Comment by hasufell** [comment]
That's understandable. I haven't really thought about the impact on the command line flags. I just use the config file.

**Comment by dnephin** [comment]
What if we were to do something like `IsFast`. Instead of having sections for linters we could support `Tags`. One default tag would be `Fast` which is applied to all the linters that are currently marked as `IsFast`.

Then to run a subset of linters you could run `gometalinter --tags dev`, and it would only run linters configured with that tag.

That way we could support multiple use cases, and a single linter could have multiple tags. We would have to make `--tags` mutually exclusive with `--enable/disable` otherwise it would be pretty confusing.

**Comment by alecthomas** [comment]
I quite like that idea, though maybe we'd have to call it something other than `tags` so as not to be confused with Go build tags. Perhaps `--select=<label>,<label>,...`
