### ISSUE TITLE
Allow disabling linters that don't understand Go modules

### ISSUE THREAD

**Issue by mjgarton** [alecthomas/gometalinter#531]
Provide an option to disable all linters that fail when using Go modules?  Something like `--disable-module-broken` for example.

If we think this is a good idea, I may try to find time to implement it.

**Comment by dnephin** [comment]
I think it might be better to create a list of the linters in an issue and document which ones have been rebuilt with module support instead of adding a flag. The flag seems strange to me because it could potentially run different linters on each release (as linters are updated) which is a weird feature to support.
