### ISSUE TITLE
Pre-install on Travis?

### ISSUE THREAD

**Issue by meatballhat** [alecthomas/gometalinter#65]
I'm the primary human responsible for build environment images at Travis CI, and I'm also a happy gometalinter user.  I'm considering pre-installing gometalinter & tools on the base image for the [Ubuntu Trusty beta](http://docs.travis-ci.com/user/trusty-ci-environment/), and possibly backporting it to the Ubuntu Precise golang image.  Questions include:

- Is this a bad idea?
- Is the addition of tagging releases possible, or can/should `master` always be considered stable?

Related PR to cookbooks that will implement the change: https://github.com/travis-ci/travis-cookbooks/pull/603

**Comment by alecthomas** [comment]
Hello there,

That would be great!

I would have no issue with tagging releases, but the problem is that the tool relies on many third party tools. Even if I tag releases, upstream changes can break it. The only real way around that is to vendor them, but I don't think I want to go down that route.

Other than that, master is always considered stable, as checked by the [Travis regression tests](https://travis-ci.org/alecthomas/gometalinter)!

Alec

**Comment by meatballhat** [comment]
@alecthomas I'm happy to move forward with the assumption that `master` is stable :smiley:  Thanks!
